/**
 * @omega/world-gen — galaxy generator.
 *
 * Produces a deterministic {@link Galaxy}: a named spiral galaxy whose star
 * systems are placed along `armCount` logarithmic spiral arms. Each system is
 * generated by {@link StarSystemGenerator}. See docs/adr/0001-determinism.md.
 */

import { Rng } from '@omega/engine-core';
import { clamp, TAU } from '@omega/engine-math';
import { StarSystem, StarSystemGenerator } from './star.js';

/** Procedural galaxy name syllables (distinct flavor from planets). */
const GALAXY_PREFIXES = [
  'And', 'Mil', 'Nox', 'Vel', 'Cyg', 'Orp', 'Eri', 'Tyr', 'Lum', 'Ser',
];
const GALAXY_SUFFIXES = [
  'axia', 'arion', 'eon', 'us', 'eth', 'ora', 'ix', 'yne', 'ara', 'um',
];

export function makeGalaxyName(rng: Rng): string {
  return rng.pick(GALAXY_PREFIXES) + rng.pick(GALAXY_SUFFIXES);
}

export interface GalaxyArmPlacement {
  systemId: string;
  /** Position in a normalized [-1, 1] galaxy plane. */
  x: number;
  y: number;
  /** Arm index this system belongs to. */
  arm: number;
  /** Distance from the galactic center in normalized units [0, 1]. */
  radius: number;
}

export interface Galaxy {
  /** Stable index label, e.g. 'GLX-0001'. */
  id: string;
  seed: number | bigint | string;
  name: string;
  armCount: number;
  /** Logarithmic spiral tightness (b in r = a*exp(b*theta)). */
  spiralTightness: number;
  starSystems: StarSystem[];
  placements: GalaxyArmPlacement[];
}

export interface GalaxyOptions {
  index?: number;
  name?: string;
  /** Number of spiral arms. Default 4. */
  armCount?: number;
  /** Number of star systems to place. Default 128. */
  systemCount?: number;
}

/**
 * Generate a galaxy deterministically from `seed`.
 *
 * Star systems are scattered along logarithmic spiral arms: for each system we
 * pick an arm, a normalized radius, the arm's base angle plus `b*theta`, and a
 * small seeded scatter so arms look organic rather than perfectly mathematical.
 */
export class GalaxyGenerator {
  private readonly seed: number | bigint | string;
  private readonly index: number;
  private readonly nameOverride?: string;
  private readonly armCount: number;
  private readonly systemCount: number;

  constructor(seed: number | bigint | string, opts: GalaxyOptions = {}) {
    this.seed = seed;
    this.index = opts.index ?? 0;
    this.nameOverride = opts.name;
    this.armCount = clamp(opts.armCount ?? 4, 1, 12);
    this.systemCount = Math.max(1, opts.systemCount ?? 128);
  }

  generate(): Galaxy {
    const rng = new Rng(`galaxy:${this.seed}`);
    const name = this.nameOverride ?? makeGalaxyName(rng);
    const spiralTightness = rng.nextRange(0.25, 0.5);

    const a = rng.nextRange(0.05, 0.15); // spiral scale
    const maxTurns = rng.nextRange(1.5, 3.0);

    const starSystems: StarSystem[] = [];
    const placements: GalaxyArmPlacement[] = [];

    for (let i = 0; i < this.systemCount; i++) {
      const arm = i % this.armCount;
      const radius = clamp(Math.pow(rng.nextF64(), 0.6), 0, 1);
      const baseAngle = (arm / this.armCount) * TAU;
      const armAngle = baseAngle + (Math.log(radius + a) / spiralTightness) * maxTurns;
      // Organic scatter (kept small near the core, larger outward).
      const scatter = rng.nextRange(-0.06, 0.06) * (0.3 + radius);
      const angle = armAngle + scatter;
      const x = Math.cos(angle) * radius;
      const y = Math.sin(angle) * radius;

      const sseed = `system-${i}:${this.seed}`;
      const sys = new StarSystemGenerator(sseed, { index: i }).generate();
      starSystems.push(sys);
      placements.push({
        systemId: sys.id,
        x,
        y,
        arm,
        radius,
      });
    }

    const id = `GLX-${String(this.index + 1).padStart(4, '0')}`;

    return {
      id,
      seed: this.seed,
      name,
      armCount: this.armCount,
      spiralTightness,
      starSystems,
      placements,
    };
  }
}
