/**
 * @omega/geology — plate tectonics simulation.
 *
 * Deterministic continental/plate generation on a unit sphere. Plates are seeded
 * as centers on a Fibonacci-sphere distribution, each with a drift velocity and a
 * crust type (oceanic | continental) chosen by seed. Over T steps the plate
 * centers move; a heightfield is then generated by accumulating the Gaussian
 * crust contribution of nearby plates and adding convergence uplift / divergence
 * thinning. Everything is a pure function of the seed via {@link Rng}.
 *
 * See docs/adr/0001-determinism.md for the determinism contract.
 */

import { Rng } from '@omega/engine-core';
import { clamp } from '@omega/engine-math';

/** Crust type ids stored in the per-cell `crustType` array. */
export const Crust = {
  Oceanic: 0,
  Continental: 1,
} as const;

export type CrustId = (typeof Crust)[keyof typeof Crust];

export interface PlateOptions {
  /** Number of plates. Default 8. */
  plateCount?: number;
  /** Heightfield resolution NxN. Default 128. */
  gridSize?: number;
  /** Number of simulation steps plates drift before sampling. Default 64. */
  steps?: number;
  /** Gaussian falloff radius (in grid cells) for crust contribution. Default 24. */
  falloff?: number;
  /** Maximum per-plate crust thickness added to the heightfield. Default 0.6. */
  maxThickness?: number;
  /** Fraction of plates that start as continental. Default 0.5. */
  continentalFraction?: number;
  /** Scale of per-step drift in grid cells. Default 0.4. */
  driftScale?: number;
  /** Multiplier for convergence uplift per overlapping pair. Default 0.25. */
  upliftScale?: number;
  /** Multiplier for divergence thinning. Default 0.15. */
  thinScale?: number;
}

interface Plate {
  /** Center on the unit sphere. */
  cx: number;
  cy: number;
  cz: number;
  /** Drift velocity (unit-sphere direction * speed). */
  vx: number;
  vy: number;
  vz: number;
  crust: CrustId;
  thickness: number;
}

export interface PlateField {
  /** Heightfield resolution. */
  n: number;
  /** Row-major NxN elevation. */
  heights: Float32Array;
  /** Row-major NxN crust type id (0 = oceanic, 1 = continental). */
  crustType: Uint8Array;
  /** Number of plates simulated. */
  plateCount: number;
}

/** State snapshot for checkpointing/resume bit-for-bit. */
export interface PlateSimState {
  rng: string[];
  plates: Array<{
    cx: number;
    cy: number;
    cz: number;
    vx: number;
    vy: number;
    vz: number;
    crust: CrustId;
    thickness: number;
  }>;
  step: number;
  steps: number;
}

/**
 * Distribute `count` points evenly on the unit sphere using the Fibonacci
 * spiral. Deterministic for a given count (no RNG needed).
 */
function fibonacciSphere(count: number): Array<[number, number, number]> {
  const pts: Array<[number, number, number]> = [];
  const golden = Math.PI * (3 - Math.sqrt(5)); // golden angle
  if (count <= 0) return pts;
  const denom = count === 1 ? 1 : count - 1;
  for (let i = 0; i < count; i++) {
    const y = 1 - (i / denom) * 2; // [1, -1]
    const radius = Math.sqrt(Math.max(0, 1 - y * y));
    const theta = golden * i;
    const x = Math.cos(theta) * radius;
    const z = Math.sin(theta) * radius;
    pts.push([x, y, z]);
  }
  return pts;
}

export class PlateSim {
  private readonly opts: Required<PlateOptions>;
  private rng: Rng;
  private plates: Plate[] = [];
  private step = 0;

  constructor(seed: number | bigint | string, options: PlateOptions = {}) {
    this.opts = {
      plateCount: options.plateCount ?? 8,
      gridSize: options.gridSize ?? 128,
      steps: options.steps ?? 64,
      falloff: options.falloff ?? 24,
      maxThickness: options.maxThickness ?? 0.6,
      continentalFraction: options.continentalFraction ?? 0.5,
      driftScale: options.driftScale ?? 0.4,
      upliftScale: options.upliftScale ?? 0.25,
      thinScale: options.thinScale ?? 0.15,
    };
    this.rng = new Rng(seed);
    this.seedPlates();
  }

  /** Seed N plates: Fibonacci centers, seeded drift, seeded crust type. */
  private seedPlates(): void {
    const n = this.opts.plateCount;
    const centers = fibonacciSphere(n);
    const continentalTarget = Math.round(n * this.opts.continentalFraction);
    // Assign crust types deterministically, then shuffle by seed.
    const crusts: CrustId[] = [];
    for (let i = 0; i < n; i++) {
      crusts.push(i < continentalTarget ? Crust.Continental : Crust.Oceanic);
    }
    this.rng.shuffle(crusts);

    this.plates = centers.map(([cx, cy, cz], i) => {
      // Drift velocity: random direction on sphere * small speed.
      const az = this.rng.nextRange(0, Math.PI * 2);
      const el = this.rng.nextRange(-1, 1); // cos-elevation in [-1,1]
      const s = Math.sqrt(Math.max(0, 1 - el * el));
      const speed = this.rng.nextRange(0.3, 1) * this.opts.driftScale;
      const crust = crusts[i]!;
      const thickness =
        crust === Crust.Continental
          ? this.opts.maxThickness
          : this.opts.maxThickness * 0.4;
      return {
        cx,
        cy,
        cz,
        vx: Math.cos(az) * s * speed,
        vy: el * speed,
        vz: Math.sin(az) * s * speed,
        crust,
        thickness,
      };
    });
  }

  /** Advance plates by one step: move centers, renormalize to unit sphere. */
  private advance(): void {
    for (const p of this.plates) {
      p.cx += p.vx;
      p.cy += p.vy;
      p.cz += p.vz;
      // Renormalize back onto the unit sphere so drift wraps the globe.
      const len = Math.sqrt(p.cx * p.cx + p.cy * p.cy + p.cz * p.cz) || 1;
      p.cx /= len;
      p.cy /= len;
      p.cz /= len;
    }
    this.step++;
  }

  /**
   * Global convergence/divergence term. For each pair of plates we estimate the
   * rate of change of their angular separation along their drift velocities:
   * approaching pairs add uplift, receding pairs thin crust. This is a coarse
   * global proxy so the field is not perfectly flat; fully deterministic.
   */
  private convergenceTerm(): number {
    const plates = this.plates;
    let uplift = 0;
    let thin = 0;
    for (let i = 0; i < plates.length; i++) {
      const a = plates[i]!;
      for (let j = i + 1; j < plates.length; j++) {
        const b = plates[j]!;
        const dot = clamp(a.cx * b.cx + a.cy * b.cy + a.cz * b.cz, -1, 1);
        const ang = Math.acos(dot);
        const aDot = a.vx * b.cx + a.vy * b.cy + a.vz * b.cz;
        const bDot = b.vx * a.cx + b.vy * a.cy + b.vz * a.cz;
        const dAngDt = -(aDot + bDot) / (Math.sin(ang) || 1e-6);
        if (dAngDt < 0) uplift += -dAngDt * this.opts.upliftScale;
        else thin += dAngDt * this.opts.thinScale;
      }
    }
    return (uplift - thin) * 0.01;
  }

  /**
   * Build the equirectangular heightfield from the current plate layout.
   *
   * Each cell (lon, lat) accumulates, over all plates, a Gaussian-weighted crust
   * thickness based on angular distance from the plate center. The dominant
   * (thickest) crust determines the cell's crust type. A global convergence term
   * adds/subtracts elevation.
   */
  private buildField(): PlateField {
    const n = this.opts.gridSize;
    const heights = new Float32Array(n * n);
    const crustType = new Uint8Array(n * n);
    const invFalloff = 1 / (this.opts.falloff * this.opts.falloff);

    const convergence = this.convergenceTerm();

    for (let y = 0; y < n; y++) {
      const lat = (y / (n - 1)) * Math.PI - Math.PI / 2; // [-PI/2, PI/2]
      const clat = Math.cos(lat);
      const slat = Math.sin(lat);
      for (let x = 0; x < n; x++) {
        const lon = (x / (n - 1)) * Math.PI * 2 - Math.PI; // [-PI, PI]
        const clon = Math.cos(lon);
        const slon = Math.sin(lon);

        let best = -Infinity;
        let bestCrust: CrustId = Crust.Oceanic;
        let acc = 0;
        for (let k = 0; k < this.plates.length; k++) {
          const p = this.plates[k]!;
          // Angular distance via dot product (both unit vectors).
          const dot =
            slat * p.cy + clat * clon * p.cx + clat * slon * p.cz;
          const ang = Math.acos(clamp(dot, -1, 1)); // [0, PI]
          // Gaussian falloff measured in grid cells (n spans PI radians).
          const dCells = (ang / Math.PI) * n;
          const w = Math.exp(-dCells * dCells * invFalloff);
          const contrib = w * p.thickness;
          acc += contrib;
          if (contrib > best) {
            best = contrib;
            bestCrust = p.crust;
          }
        }
        const idx = y * n + x;
        heights[idx] = acc + convergence;
        crustType[idx] = bestCrust;
      }
    }

    return { n, heights, crustType, plateCount: this.plates.length };
  }

  /** Run the simulation and return the final heightfield + crust map. */
  simulate(): PlateField {
    this.step = 0;
    for (let s = 0; s < this.opts.steps; s++) {
      this.advance();
    }
    return this.buildField();
  }

  /** Run one simulation step (advance plates). Returns current step count. */
  stepOnce(): number {
    this.advance();
    return this.step;
  }

  /** Build the heightfield from the current plate layout without advancing. */
  current(): PlateField {
    return this.buildField();
  }

  /** Snapshot internal state (RNG + plates + step) for exact resume. */
  state(): PlateSimState {
    return {
      rng: this.rng.state(),
      plates: this.plates.map((p) => ({
        cx: p.cx,
        cy: p.cy,
        cz: p.cz,
        vx: p.vx,
        vy: p.vy,
        vz: p.vz,
        crust: p.crust,
        thickness: p.thickness,
      })),
      step: this.step,
      steps: this.opts.steps,
    };
  }

  /** Restore from a snapshot produced by {@link state}. */
  setState(s: PlateSimState): void {
    this.rng.setState(s.rng);
    this.plates = s.plates.map((p) => ({ ...p }));
    this.step = s.step;
  }
}
